version: '3.1'

services:
  
  mongodb:
    image: mongo
    #    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongolito
    ports:
      - "27017:27017"
    volumes:
      - /home/teruel/mongodb/database:/data/db
    networks:
      - mongo-compose-network
  
#  mongo-express:
#    image: mongo-express
#    #    restart: always
#    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: teruel
#      ME_CONFIG_BASICAUTH_PASSWORD: abc123
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: mongolito
#      ME_CONFIG_MONGODB_URL: mongodb://root:mongolito@localhost:27017
#    ports:
#      - "8081:8081"
#    links:
#      - mongodb
#    networks:
#      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge